import {
  AlertTriangle,
  Archive,
  ArrowLeftRight,
  ArrowRight,
  BarChart3,
  BookOpen,
  BookOpenText,
  BookMarked,
  BusFront,
  Cake,
  CalendarDays,
  ChartPie,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleEllipsis,
  CloudUpload,
  Database,
  Download,
  Droplets,
  Eye,
  FileDown,
  FileUp,
  Gift,
  HandCoins,
  HandHeart,
  Heart,
  History,
  ImagePlus,
  ImageUp,
  Laptop,
  LayoutDashboard,
  Loader2,
  Lock,
  Pencil,
  PiggyBank,
  Plus,
  RotateCcw,
  Search,
  Settings,
  ShieldCheck,
  Sparkles,
  Tags,
  Trash2,
  TrendingDown,
  TrendingUp,
  Upload,
  Users,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
  X,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const MAP_IKON: Record<string, LucideIcon> = {
  Archive,
  BookOpen,
  BookOpenText,
  BookMarked,
  BusFront,
  Cake,
  CalendarDays,
  CircleEllipsis,
  Droplets,
  Gift,
  HandCoins,
  HandHeart,
  Heart,
  PiggyBank,
  Users,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
};

export const IKON_UI: Record<string, LucideIcon> = {
  alert: AlertTriangle,
  net: ArrowLeftRight,
  panah: ArrowRight,
  chart: BarChart3,
  pie: ChartPie,
  cek: Check,
  bawah: ChevronDown,
  kiri: ChevronLeft,
  kanan: ChevronRight,
  cloud: CloudUpload,
  db: Database,
  unduh: Download,
  fileDown: FileDown,
  fileUp: FileUp,
  laptop: Laptop,
  dashboard: LayoutDashboard,
  muat: Loader2,
  lock: Lock,
  edit: Pencil,
  history: History,
  foto: ImagePlus,
  plus: Plus,
  reset: RotateCcw,
  cari: Search,
  settings: Settings,
  shield: ShieldCheck,
  sparkle: Sparkles,
  ganti: ImageUp,
  tag: Tags,
  hapus: Trash2,
  naik: TrendingUp,
  turun: TrendingDown,
  lihat: Eye,
  unggah: Upload,
  tutup: X,
  tilawah: BookMarked,
};

/** Ikon berdasarkan nama string (dipakai kategori) dengan fallback aman. */
export function IkonKategori({ nama, className }: { nama: string; className?: string }) {
  const Icon = MAP_IKON[nama] ?? CircleEllipsis;
  return <Icon className={className} aria-hidden="true" />;
}